# This workflow sets up a CI/CD pipeline for Terraform on AWS using GitHub Actions.
# It initializes Terraform, plans the infrastructure changes, waits for manual approval,
name: Terraform AWS CI/CD Pipeline
# applies the changes, waits for 2 hours, and then destroys the infrastructure.

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

    # Auto-approval: No manual approval step required, proceeding automatically.

      - name: Terraform Apply
        if: ${{ success() }}
        run: terraform apply -auto-approve tfplan

      - name: Wait 2 hours before destroy
        if: ${{ success() }}
        run: sleep 600

      - name: Terraform Destroy
        if: ${{ success() }}
        run: terraform destroy -auto-approve